repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: flake8
        name: flake8 (with unused imports)
        entry: flake8 --select=F401
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: flake8-import-order
        name: flake8 import order
        entry: flake8-import-order
        language: system
        types: [python]
